# Project information
site_name: "Open Active Management Technology Cloud Toolkit"
site_url: "https://open-amt-cloud-toolkit.github.io/docs"
repo_url: "https://github.com/open-amt-cloud-toolkit/open-amt-cloud-toolkit"
repo_name: "open-amt-cloud-toolkit/open-amt-cloud-toolkit"
copyright: "Copyright &copy; 2021 Intel Corporation"
site_dir: site/2.15
# Configuration
theme:
  name: "material"
  language: "en"
  logo: "assets/images/logo-white-75px.png"
  font:
    text: "Roboto"
    code: "Roboto Mono"
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.instant
    - search.suggest
    - search.highlight
    - navigation.top
    - toc.integrate
  custom_dir: ./docs/overrides
  palette:
    # Palette toggle for automatic mode
    # - media: "(prefers-color-schemes)"
    #   toggle:
    #     icon: material/brightness-auto
    #     name: Switch to dark mode
    
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: custom 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
# Page tree
nav:
  - Home:
    - Overview: index.md
    - Announcements: announcements.md
    - Release Notes: release-notes.md
    - Video Walkthroughs: videos.md
    - License: license.md
    - Get Help:
      - Troubleshooting: Reference/troubleshooting.md
  - Get Started:
    - Prerequisites: GetStarted/prerequisites.md
    - Set Up: GetStarted/setup.md
    - Configure:
      - Login to Sample Web UI: GetStarted/loginToUI.md
      - Create a CIRA Config: GetStarted/createCIRAConfig.md
      - Create an AMT Profile:
        - Create a Profile with CCM: GetStarted/createProfileCCM.md
        - Create a Profile with ACM: GetStarted/createProfileACM.md
    - Connect:
      - Build & Run RPC: GetStarted/buildRPC.md
      - Manage AMT Device: GetStarted/manageDevice.md
    - Get Help:
      - Troubleshooting: Reference/troubleshooting.md
  - Deployment:
    - Overview: Deployment/overview.md
    - Centralized Configuration: Deployment/centralizedConfiguration.md
    - Database Replacement: Deployment/database.md
    - Secrets Management: Deployment/secrets.md
    - Upgrade Toolkit Version: Deployment/upgradeVersion.md
  - Tutorials:
    - UI Toolkit KVM Module: Tutorials/uitoolkitReact.md
    - REST API Call: Tutorials/apiTutorial.md
    - Wireless Activation: Tutorials/createWiFiConfig.md
    - Modify User Authentication: Tutorials/modifyUserAuth.md
    - Scaling Tutorials:
      - Overview: Tutorials/Scaling/overview.md
      - Docker Swarm*: Tutorials/Scaling/docker-swarm.md
      - Kubernetes Deployments:
        - Kubernetes (K8s): Tutorials/Scaling/Kubernetes/deployingk8s.md
        - AKS: Tutorials/Scaling/Kubernetes/deployingk8s-aks.md
        - EKS: Tutorials/Scaling/Kubernetes/deployingk8s-eks.md
        - KUMA Service Mesh: Tutorials/Scaling/Kubernetes/service-mesh.md
    - Get Help:
        - Troubleshooting: Reference/troubleshooting.md
  - Reference:
    - Architecture Overview: Reference/architectureOverview.md
    - AMT Power States: Reference/powerstates.md
    - GUIDs in Intel® AMT: Reference/guids.md
    - Logging: Reference/logging.md
    - Middleware Extensibility: Reference/middlewareExtensibility.md
    - Production Mode Vault: Reference/productionVault.md
    - SSL with Local Postgres: Reference/sslpostgresLocal.md
    - Enterprise Assistant:
      - Overview: Reference/EA/overview.md
      - 802.1x Configuration: Reference/EA/ieee8021xconfig.md
    - Event Monitoring (MQTT):
      - Customizing MQTT Events: Reference/MQTT/customMqttEvents.md
      - Viewing MQTT Events: Reference/MQTT/viewMqttEvents.md
    - Management Presence Server:
      - Configuration: Reference/MPS/configuration.md
      - Security Information: Reference/MPS/securityMPS.md
    - Remote Provisioning Server:
      - Configuration: Reference/RPS/configuration.md
      - Security Information: Reference/RPS/securityRPS.md
      - Create Profile with TLS: Reference/RPS/createProfileTLSConfig.md
    - Remote Provisioning Client:
      - Build & Run RPC: Reference/RPC/buildRPC_Manual.md
      - RPC CLI: Reference/RPC/commandsRPC.md
      - RPC Library: Reference/RPC/libraryRPC.md
    - UI Toolkit:
      - Controls:
        - Keyboard, Video, Mouse: Reference/UIToolkit/Controls/kvmControl.md
        - Serial Over LAN: Reference/UIToolkit/Controls/serialOverLANControl.md
      - Localization: Reference/UIToolkit/localization.md
      - React Bundles:
        - Keyboard, Video, Mouse: Reference/UIToolkit/Bundles/kvmReact.md
        - Serial Over LAN: Reference/UIToolkit/Bundles/serialOverLANReact.md
      - Webpack Configuration: Reference/UIToolkit/webpackConfig.md
    - Intel&reg; MEBX:
      - DNS Suffix: Reference/MEBX/dnsSuffix.md
      - Unprovisioning: Reference/MEBX/unprovision.md
    - Certificates:
      - Custom Provisioning Certificate: Reference/Certificates/generateProvisioningCert.md
      - Provisioning Certificate: Reference/Certificates/remoteProvisioning.md
      - TLS Certificate: Reference/Certificates/tls.md
    - Get Help:
      - Troubleshooting: Reference/troubleshooting.md
  - APIs:
    - Management Presence Server: APIs/indexMPS.md
    - Remote Provisioning Server: APIs/indexRPS.md
# Extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - abbr
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      # make exceptions to highlighting of code:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true
extra_css:
  - assets/stylesheets/branding.css
  - assets/stylesheets/index.css
  - assets/stylesheets/videos.css

plugins:
  - render_swagger
  - search
  - macros
  - img2fig
extra:
  version:
    provider: mike
    default:
      - rapid
      - lts
  repoVersion:
    mpsAPI: 2.11.0
    rpsAPI: 2.16.0
    oamtct: 2.14.0
    rpc_go: 2.14.2
    rpc_c: 2.0.0
    ui_toolkit: 2.0.10
    ui_toolkit_react: 3.0.2
    ui_toolkit_angular: 6.0.1
  docsSite:
    ltsVersion: 2.0
  analytics:
    provider: google
    property: "G-00QEDJW2TS"
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
